version: "3.8"
services:
  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: aether
      POSTGRES_DB: aether
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata: